def main():
    int a = 7
    print(a * 0)
    print(0 * a)
    print(a * 1)
    print(1 * a)
    print(a * 8)
    print(8 * a)
    print(a * 9)
    print(a * 7)
    print(a * 15)
    print(a * 16)
    print(a * 17)
    print(a * 31)
    print(a * 33)
    print(a + 0)
    print(0 + a)
    print(a - 0)
    print(a ^ a)
    print(-5 ^ -5)
    print(3 * 0)
    print(123 * 1)
    print(123 % 1)
    print(123 // 1)
    print(7 * 32)
    print(-3 * 8)
    print(64 * 16)
    print("\n")
    int x = 5
    x = (x << 2)
    print(x)
    x = (x << 3)
    print(x)
    int y = 3
    y = (y << 1) << 4
    print(y)
    int z = 10
    print(z * 5)
    print(z * 6)
    print(z * 11)
    int w = -6
    print(w * 4)
    print(w * 3)