name: Cpyte CI

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Ubuntu
            arch: x86_64
            runner: ubuntu-24.04

          - os: Ubuntu
            arch: arm64
            runner: ubuntu-24.04-arm

          - os: macOS
            arch: arm64
            runner: macos-14

          - os: macOS
            arch: x86_64
            runner: macos-13

          - os: Windows
            arch: x86_64
            runner: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run Cpyte tests
        run: python scripts/test_cpy.py
